### ISSUE TITLE
ML WG Meeting #2 Scheduling Thread

### ISSUE THREAD

**Issue by nbren12** [pangeo-data/ml-workflow-examples#1]
Hi everyone!  Let's try to schedule the next meeting of the ML working group. I will be out of town during the second half of February, so I suggest we meet the week of 3/4. If you are interested in attending here is scheduling poll: https://www.when2meet.com/?7490323-4yauU

I tried to mention all the people on the last thread, but please CC anyone that I missed. Thanks!

cc @gmaze @jhamman @RPrudden @rabernat @dgagne @leifdenby @djgagne @raspstephan @alando46 @svadams @pbranson @duncanwp @mrocklin  @TomAugspurger @ktyle 
related to https://github.com/pangeo-data/pangeo/issues/532

**Comment by alando46** [comment]
Haha @nbren12 trying to get us to sign up for as many scheduling services as possible eh? :)

**Comment by nbren12** [comment]
Pretty much! We can make a poll about which one to use for the next meeting
;)

**Comment by raspstephan** [comment]
@rabernat You mentioned a repository for ML use cases. Could you point me to that? I will have a neural network data loading example soon.

**Comment by rabernat** [comment]
This is it! I just have not managed to upload my examples yet, but don't let that stop you.

Just make a PR on this repo with your example.

**Comment by raspstephan** [comment]
Ok... I am stupid... Example coming soon.

**Comment by nbren12** [comment]
Okay, looks like many more people have participted in that poll in the past few days.  So far **9AM-10AM PST on March 4 seems like the best option**. I think we should schedule the meeting for that slot. If you agree, please thumbs up this post, otherwise, thumbs down.

@jhamman and @dgagne. Once a few people confirm for that time, would one of you be able to setup a Google Meet again?

P.S. Thanks for making that PR @raspstephan.

**Comment by raspstephan** [comment]
Do we have an agenda for today's meeting?

**Comment by djgagne** [comment]
I just created a google meet for the event and will post the link here just before the meeting. Sorry for the short notice on that. @raspstephan we can go through your notebook during the meeting at least.

**Comment by raspstephan** [comment]
Yes, we can go through it!

**Comment by nbren12** [comment]
Great! Thanks again for setting up that google meet again, David. Here is a link to an agenda document we can use to take notes: https://paper.dropbox.com/doc/Meeting-notes-ML-WG-Meeting-2--AYoxuO4cf_aoPVZ30DWYjQEaAQ-xOE0uGGLjsnJAyw5At51x.

I will have to leave 15 minutes early today.

**Comment by alando46** [comment]
what's the meeting link @nbren12

**Comment by djgagne** [comment]
The video link is at https://meet.google.com/xed-ikmi-qko.

**Comment by rabernat** [comment]
I am coming but will be a few minutes late

**Comment by RPrudden** [comment]
Sorry to have missed this meeting, I was unwell. Look forward to catching up.
