### ISSUE TITLE
Meeting #5

### ISSUE THREAD

**Issue by nbren12** [pangeo-data/ml-workflow-examples#10]
Hi everyone! We had discussed meeting next Monday (August 5) at 9AM PDT. Here is a link to the [agenda](https://paper.dropbox.com/doc/Meeting-notes-Machine-Learning-WG--AiG7hhjX8zJj6NdsZc3nh3EAAQ-9UUgyywF9jmIMXXbmZTyJ), which is currently empty. Please add any topics you would like to discuss and invite anyone you would like to join. The video-conferencing information is below.

cc @raspstephan @rabernat @jhamman @mrocklin @TomAugspurger @jbednar @djgagne @mcgibbon 

# Zoom Info
Time: Aug 5, 2019 09:00 AM Pacific Time (US and Canada)

Join from PC, Mac, Linux, iOS or Android: https://vulcan.zoom.us/j/5609334887

Or iPhone one-tap :
    US: +16699006833,,5609334887#  or +16468769923,,5609334887# 
Or Telephone：

   
Dial(for higher quality, dial a number based on your current location)：
        US: +1 669 900 6833  or +1 646 876 9923 
        United Kingdom: +44 203 051 2874  or +44 203 481 5237  or +44 203 966 3809  or +44 131 460 1196 
        South Africa: +27 87 551 7702  or +27 87 550 7717 
    Meeting ID: 560 933 4887
    International numbers available: https://zoom.us/u/asGKwYILw

This meeting is subject to being recorded.  If recorded, you will see a red dot in the upper left hand corner of the display.  By accepting this meeting, you are consenting to the recording.  Please decline the meeting and contact the meeting organizer if you have any concerns regarding the recording.

Or Skype for Business (Lync):
    https://vulcan.zoom.us/skype/5609334887

**Comment by jhamman** [comment]
Would it be worth making this the standard meeting time for the WG? 1st Monday of every month, 9a PT? We could add this to the Pangeo meeting calendar which would hopefully cut down on scheduling overhead going forward? Thoughts?

**Comment by nbren12** [comment]
That would be really helpful @jhamman!

**Comment by jhamman** [comment]
Okay, done! It's now on the calendar: https://pangeo.io/meeting-notes.html (see GCAL/ICAL links).

**Comment by nbren12** [comment]
Great thanks Joe!

**Comment by nbren12** [comment]
cc @raspstephan @rabernat @jhamman @mrocklin @TomAugspurger @jbednar @djgagne @mcgibbon

Hey everyone. I just wanted to remind you we are meeting this Monday at 9AM PDT just in case you didn’t add the pangeo calendar to your personal one. (zoom details below)

/Hi there, 

Noah Brenowitz is inviting you to a scheduled Zoom meeting. 

Topic: Pangeo ML working group
Time: Sep 9, 2019 09:00 PM Pacific Time (US and Canada)

Join from PC, Mac, Linux, iOS or Android: https://vulcan.zoom.us/j/656667817

Or iPhone one-tap :
    US: +16699006833,,656667817#  or +16468769923,,656667817# 
Or Telephone：
    Dial in from Vulcan: 2990 or 206-342-2990

    Dial(for higher quality, dial a number based on your current location)：
        US: +1 669 900 6833  or +1 646 876 9923 
        United Kingdom: +44 203 966 3809  or +44 131 460 1196  or +44 203 051 2874  or +44 203 481 5237 
        South Africa: +27 87 551 7702  or +27 87 550 7717 
    Meeting ID: 656 667 817
    International numbers available: https://zoom.us/u/asGKwYILw

This meeting is subject to being recorded.  If recorded, you will see a red dot in the upper left hand corner of the display.  By accepting this meeting, you are consenting to the recording.  Please decline the meeting and contact the meeting organizer if you have any concerns regarding the recording.


Or an H.323/SIP room system:
    H.323: 
        162.255.37.11 (US West)
        162.255.36.11 (US East)
        221.122.88.195 (China)
        115.114.131.7 (India)
        213.19.144.110 (EMEA)
        103.122.166.55 (Australia)
        209.9.211.110 (Hong Kong)
        64.211.144.160 (Brazil)
        69.174.57.160 (Canada)
        207.226.132.110 (Japan)
    Meeting ID: 656 667 817

    SIP: 656667817@zoomcrc.com

Or Skype for Business (Lync):
    https://vulcan.zoom.us/skype/656667817

**Comment by rabernat** [comment]
I would like to join this one and discuss some experiments I have been doing using prefect for ETL workflows.

**Comment by nbren12** [comment]
I would love to hear about prefect. I've been using snakemake for so long, but I feel like I'm stuck in a local minimum.

**Comment by cicdw** [comment]
Hello! @mrocklin mentioned this meeting to me - I’m the principal maintainer of Prefect and would be interested in joining tomorrow to hear more about how this group is using Prefect and whether there’s anything we could do to make it more useful for your workflows. I intend to be more of a passive listener but would be happy to answer any questions as well. I hope that’s alright!

**Comment by nbren12** [comment]
link to agenda: https://paper.dropbox.com/doc/Meeting-notes-Machine-Learning-WG--AkeIE2HHjqKpN6SraJhELuL6AQ-9UUgyywF9jmIMXXbmZTyJ

**Comment by mrocklin** [comment]
I'm trying to join with the link above and I'm getting a message that says "The host has another meeting in progress".  Any tips?

**Comment by TomAugspurger** [comment]
@mrocklin: this link? https://vulcan.zoom.us/j/656667817

**Comment by TomAugspurger** [comment]
The original post is an older link I think.

**Comment by nbren12** [comment]
Here is the zoom link for tomorrow’s meeting: https://vulcan.zoom.us/j/547536123

Here is the Dropbox paper agenda we’ve been using for the last couple of meetings: https://paper.dropbox.com/doc/Meeting-notes-Machine-Learning-WG-9UUgyywF9jmIMXXbmZTyJ

I realize I left this to the very last moment, so I don’t expect much turn out. If you want to attend, please hit thumbs up on this post so I know who to expect. Thanks!

**Comment by djgagne** [comment]
I will be late because I have a short meeting at 10 AM but will still try to call in if there is a quorum.

**Comment by nbren12** [comment]
Hey. Just a reminder that we are meeting tomorrow morning! See details here: https://pangeo.io/meeting-notes.html.

Hangout link: https://meet.google.com/ubc-tgak-ugg

**Comment by TomAugspurger** [comment]
I'll be unable to attend. I'm giving a talk on Scalable Machine Learning at
the same time :)

**Comment by raspstephan** [comment]
I can talk (again... briefly) about the weather forecasting dataset we are building. If @djgagne is here, we can talk about how that could integrate with NCARs efforts.

**Comment by gmaze** [comment]
I won't be able to attend this one either (I'm on a meeting out of office)

**Comment by djgagne** [comment]
I will able to attend this morning.

**Comment by rabernat** [comment]
Hi everyone...I won't be able to make the meeting today. I'm actually at PyData NYC, and @TomAugspurger's talk about Scaling Machine Learning with Dask is happening at the exact same time!

Thanks for keeping this going.

**Comment by nbren12** [comment]
Hey everyone. I am on vacation tomorrow, so I won’t be able to attend to the first ML working group meeting of the new year. Feel free to meet or not without me, the meeting information is listed on the pangeo website as usual. I will touch base with one of you afterwards to see how it went.

cc @jhamman @djgagne @raspstephan

**Comment by djgagne** [comment]
Our next meeting is on Monday at 9 AM pacific time. Does anyone want to present on recent work or want to suggest a discussion topic? 
@nbren12 @jhamman @rabernat @raspstephan

**Comment by raspstephan** [comment]
I’ve talked about the weather forecasting benchmark before but it’s now 99% done so I could briefly present it again along with the data loading challenge it presents. Related to that I would be interested if @djgagne  could talk about the benchmarks you are preparing. If @rabernat can make it I would also love to talk about ways to put the data on the cloud. Does this sounds good?

**Comment by nbren12** [comment]
Those sounds like good discussion points @raspstephan. I've been thinking about how ML parameterization research is 99% data munging/compiling GCMs and 1% ML, haha.

**Comment by djgagne** [comment]
I will be able to discuss some of the progress and challenges we have made with the benchmark dataset project. See y'all in 45 minutes!

**Comment by raspstephan** [comment]
Zoom? Hangout? Link?

**Comment by djgagne** [comment]
Here is the hangout link: https://meet.google.com/ubc-tgak-ugg

**Comment by zhonghua-zheng** [comment]
It was a nice meeting! My computer was out of power...
When will be our next meeting?

Best regards,
Zhonghua

On Feb 3, 2020, at 10:53, Stephan Rasp <notifications@github.com> wrote:

﻿

Zoom? Hangout? Link?

**Comment by djgagne** [comment]
The meetings are scheduled on the first Monday of every month at 9 AM Pacific Time. See [here](https://pangeo.io/meeting-notes.html) for details about the ML and other Pangeo working group meetings.

**Comment by nbren12** [comment]
Is anyone meeting right now? I can't get in the room.

**Comment by jhamman** [comment]
Hi all, it sounds like we missed this months meeting. Should we try again next week? I'll suggest Tuesday 9a PT? 

Also, @nbren12, on behalf of our friends at USGS (@jsadler2) who can't access Dropbox pages, would it be possible to relocate the running meeting notes to something like GoogleDocs of HackMD?

cc @salvis2

**Comment by nbren12** [comment]
Sure. 9AM next tuesday works.

I like that dropbox paper can collapse headings, and that it has been more shareable in my experience than google docs where I often seem to get access denied errors. Is the issue that the USGS blocks dropbox.com?

**Comment by djgagne** [comment]
I have a conflict with 9 AM Pacific time next Tuesday. Would it be possible to push it to 10 AM PT instead?

David John Gagne

**Comment by jhamman** [comment]
> Is the issue that the USGS blocks dropbox.com?

Yes.

**Comment by nbren12** [comment]
> > Is the issue that the USGS blocks dropbox.com?
> 
> Yes.

That is unfortunate. Can we be guaranteed that all employers allow access to google drive or hackmd? Just trying to figure out what the lowest common denominator is.

**Comment by jhamman** [comment]
+1 for me on 10a PT next tuesday. 

> That is unfortunate. Can we be guaranteed that all employers allow access to google drive or hackmd? Just trying to figure out what the lowest common denominator is.

No, we can't be guaranteed of anything :). But we haven't had problems with google docs with our weekly Pangeo meetings so we're pretty safe.

**Comment by jsadler2** [comment]
10 A PT on Tuesday works for me too. Google docs and hackmd would both work for me to access. Not sure why USGS blocks dropbox

**Comment by HamedAlemo** [comment]
10am PT on Tuesday works for me too.

**Comment by nbren12** [comment]
Closing this scheduling thread in lieu of #12.
