### ISSUE TITLE
April 6 meeting

### ISSUE THREAD

**Issue by nbren12** [pangeo-data/ml-workflow-examples#12]
Who is planning on joining this Monday? Please thumbs up this post if you are planning to attend. Thanks.

**Comment by rabernat** [comment]
I have not joined in a while, but I’d love to share a bit about some recent progress we have have made on ocean mesoscale heat fluxes.

**Comment by nbren12** [comment]
That’d be great to hear about.

**Comment by djgagne** [comment]
I have put together a [Python Packaging Best Practices Guide](https://docs.google.com/document/d/e/2PACX-1vSgrgkdTZxp4fDXCNYVAZ5iAlYCRtb-uCAHkyH95JV__47mL0TpFsVW_cTKFvY2pZLmlwJKg9b3Tp7o/pub) that provides a high level summary of how to set up a Python package repository, use git and Github, and utilize different software engineering tools. My group has found it really useful just having all this information in one place. I suspect most of the information in the document is common knowledge for many of the attendees of this meeting, but there are a lot of scientists with less coding experience who could benefit from more guidance in these areas.

**Comment by rabernat** [comment]
Are we using the same vulcan zoom link as last time?

**Comment by nbren12** [comment]
no it's the google meet listed in the meeting notes: https://meet.google.com/ubc-tgak-ugg

**Comment by nbren12** [comment]
I will be joining at 9am. Is anyone else planning to be there?

**Comment by rabernat** [comment]
Unfortunately I have a conflict today and can't make it.

Thanks for your continued efforts at organizing this group.

**Comment by nbren12** [comment]
haha. sometimes it's more continuous than others.

**Comment by TomAugspurger** [comment]
I can join.

**Comment by nbren12** [comment]
I am asking to join...not sure if anyone is in there...

**Comment by TomAugspurger** [comment]
Perhaps we switch to whereby.com/pangeo (today and ongoing?)
