### ISSUE TITLE
Monday June 1 Meeting

### ISSUE THREAD

**Issue by nbren12** [pangeo-data/ml-workflow-examples#13]
Hey everyone. Let's meet this Monday. I'd be interested to discuss data pipelines, file formats, and workflow orchestration. I recently wrote a package to help generate complicated synthetic xarray datasets for regression testing purposes.

**Comment by nbren12** [comment]
I also finished [a draft](https://gist.github.com/nbren12/057016069e1d68f40cf659a6fbb3c61f) of a long-discussed blog post. I would appreciate your feedback.

cc @rabernat @jhamman

**Comment by djgagne** [comment]
I will be able to attend today and can provide some updates on AI4ESS summer school plans and experience running a deep learning interpretation model in real-time.

**Comment by rabernat** [comment]
I will join as well.

**Comment by nbren12** [comment]
Ok. I am asking to join the room. Do you need to let me in @djgagne?

**Comment by djgagne** [comment]
Yes. Let me log in relaly fast.
