### ISSUE TITLE
Monday, July 6 Meeting

### ISSUE THREAD

**Issue by djgagne** [pangeo-data/ml-workflow-examples#14]
Hey everyone! 

For our meeting scheduled today, I can talk about the results of the AI4ESS Summer School and some of my experiences using Jupyterhub on AWS for 300 people doing ML tasks. There were a lot of lessons learned from the experience.

**Comment by nbren12** [comment]
Hi @djgagne! I'm excited to hear how it went. I'm waiting to be let in the room if you are on.
