### ISSUE TITLE
ML WG Meeting #3

### ISSUE THREAD

**Issue by nbren12** [pangeo-data/ml-workflow-examples#7]
Let's try to schedule a meeting in the next couple of weeks or so. It would be great to hear what progress if any has been made since we last met.

Please fill out your availability if you would like to attend: https://www.when2meet.com/?7694198-KiO1S

We should probably discuss setting up a more regular schedule during the meeting.

**Comment by jhamman** [comment]
I would vote for a regular monthly meeting at a set time. We can add this to the Pangeo [calendar](http://pangeo.io/meeting-notes.html#meeting-calendar) to make communication easier too.

**Comment by jhamman** [comment]
@nbren12 - this seems to have slipped. Can we revive this?

**Comment by nbren12** [comment]
@jhamman yes it has. Only 3 people replied to the last poll, so I think I will just propose a couple of times. Can people do next week? Here are a couple of times I think might work for people:
1. 9AM  PDT on Monday (4/29),
2. 9AM PDT on Thursday (5/2), or
3. 9AM PDT on Friday (5/3)

Please respond with your preference here.

**Comment by nbren12** [comment]
Note that all those times are PDT.

**Comment by jbednar** [comment]
2/24?

**Comment by jbednar** [comment]
Assuming Monday is 4/29, all those times are good for me.

**Comment by nbren12** [comment]
Oh whoops. I just fixed that typo in the date.

**Comment by rabernat** [comment]
All times work for me! I have some new examples to share and some questions for the group.

**Comment by nbren12** [comment]
> All times work for me!

@rabernat is that really you?

**Comment by raspstephan** [comment]
I am also available for all of the options.

**Comment by jhamman** [comment]
The Monday and Thursday options work for me.

**Comment by nbren12** [comment]
@djgagne I completely forgot which day you told me you were free. Monday or Thursday are looking pretty good ATM.

**Comment by nbren12** [comment]
Actually, Thurs isn't so great for me anymore. Monday at 9AM PDT would be ideal, so let's go for that option. @jhamman, would you be able to set up a google meet for that time?

**Comment by jhamman** [comment]
call in details for the meeting:


Join Hangouts Meet
https://meet.google.com/kqr-ewex-rnj

Meeting ID
meet.google.com/kqr-ewex-rnj

Phone Numbers
‎(‪US‬)
‪+1 915-308-1847‬
Event will include a link to view full list of phone numbers for all supported countries.
PIN: ‪724 521#‬
This phone number has been selected based on the conference creator's Country setting. Learn more

**Comment by nbren12** [comment]
Thanks Joe!

**Comment by djgagne** [comment]
I will be there this morning.

**Comment by rabernat** [comment]
I will share this example:
https://github.com/rabernat/local_stencil_ml_examples

~Unfortunately something is broken with the binder, so it doesn't work interactively yet.~

_Edit:_ I got the binder working:
[![Binder](https://binder.pangeo.io/badge_logo.svg)](https://binder.pangeo.io/v2/gh/rabernat/local_stencil_ml_examples/master)

**Comment by nbren12** [comment]
Here is a link to the meeting notes: https://paper.dropbox.com/doc/Meeting-notes-2019-04-29-ML-WG--AcLJ7kkyLCTVc~RhHTvvMQkwAQ-QmhouixHxwuUWaqYXoibb

**Comment by djgagne** [comment]
If we have time, I can also discuss the parallel partial dependence plot notebook I just put together and issued a pull request for.

**Comment by nbren12** [comment]
thanks for meeting today everyone. Let's try to set up the next meeting. One month from today is memorial day. Is the next day good for people? That would be 9AM PDT on 5/28.

**Comment by djgagne** [comment]
That day works for me.

**Comment by jbednar** [comment]
It's ok for the first 30 min, which is fine for me.

**Comment by rabernat** [comment]
I updated my example notebook. @redouanelg found the problem with my CNN: I applied ReLU on the final output stage. Eliminating this and making a few tweaks allowed the CNN to do a bit better. But it is still not as good as the local fully connected NN.

I would say that this interaction is a great example of the sort of collaboration I am hoping this WG can help promote! Thanks @redouanelg!!!

**Comment by TomAugspurger** [comment]
https://github.com/pangeo-data/ml-workflow-examples/issues/7#issuecomment-487742515 proposed today at 9AM PDT, which I think was 2 minutes ago. Does anybody have things to talk about? Should re reschedule for a later date?

**Comment by nbren12** [comment]
Whoops. Looks like I let this one slide. Sorry everyone. How about this time next week (9AM PDT on 6/4)?

**Comment by TomAugspurger** [comment]
Works for me.

**Comment by djgagne** [comment]
It works for me as well. I can set up a google meet event once the time is finalized.

**Comment by nbren12** [comment]
I can do tomorrow at 9AM if that still works for you @TomAugspurger  and @djgagne. Would you mind setting up a google meet, David. If not, then we can delay further.

**Comment by TomAugspurger** [comment]
Works for me. I don't have anything to report on at this time, but am
interested to hear discussions / answer questions.

**Comment by djgagne** [comment]
I have another conference call going from 8-10 AM PT, so I likely won’t be able to make it except for a short drop in. I have created a Google Meet for the event:
https://meet.google.com/yaf-midf-nwn

**Comment by nbren12** [comment]
Okay. Thanks David. I will log into that room at 9AM. If there isn't a lot of attendance we can use it to coordinate the next meeting!

**Comment by rabernat** [comment]
I can stop in for 30 minutes!

**Comment by nbren12** [comment]
@djgagne Looks like I need someone to let me in the Google Meet room. Is anyone in there?

**Comment by TomAugspurger** [comment]
We can also jump in https://appear.in/pangeo if needed.

**Comment by djgagne** [comment]
I am letting people in now.

**Comment by nbren12** [comment]
Thanks

agenda link: https://paper.dropbox.com/doc/ML-WG-3--AeYVIwKZ08VdVD0BqQpdYaGTAQ-oXctWmAaboPfutuc4x4kB

**Comment by rabernat** [comment]
I guys, I showed up late (around 12:30) and couldn't get into the meeting room. Maybe you already finished?

**Comment by nbren12** [comment]
Sorry @rabernat! I think David was the only one who could let anyone in, and he had to leave the call around then. I should have been monitoring the github issue more closely. 

We are planning the next meeting for Monday July 1 at 9AM PDT. Can we add this to the Pangeo calendar @jhamman?
